"""Update user and profile

Revision ID: d0e6d5ecbd30
Revises: 31cc7f5ea76d
Create Date: 2025-03-18 13:16:57.277409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e6d5ecbd30'
down_revision: Union[str, None] = '31cc7f5ea76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_profile_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_profile_id_fkey', 'users', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'user_id')
    # ### end Alembic commands ###
